export const subjectList = [
    {
        id:0,
        name:'english',
        title:'English',
        description:''
    },
    {
        id:1,
        name:'art-history',
        title:'Art History',
        description:''
    }, 
    {
        id:2,
        name:'drama',
        title:'Drama',
        description:''
    },
    {
        id:3,
        name:'l1-maths',
        title:'Level 1 Maths',
        description:''
    },
    {
        id:4,
        name:'calculus',
        title:'Calculus',
        description:''
    },
    {
        id:5,
        name:'statistics',
        title:'Statistics',
        description:''
    },
    {
        id:6,
        name:'chemistry',
        title:'Chemistry',
        description:''
    },
    {
        id:7,
        name:'biology',
        title:'Biology',
        description:'',
    },
    {
        id:8,
        name:'physics',
        title:'Physics',
        description:'',
    },
    {
        id:9,
        name:'classics',
        title:'Classics',
        description:'',
    },
    {
        id:10,
        name:'history',
        title:'History',
        description:'',
    },
    {
        id:11,
        name:'geography',
        title:'Geography',
        description:'',
    },
    {
        id:12,
        name:'agbusiness',
        title:'Agribusiness',
        description:'',
    },
    {
        id:13,
        name:'economics',
        title:'Economics',
        description:'',
    },
    {
        id:14,
        name:'business-studies',
        title:'Business Studies',
        description:'',
    },
    {
        id:15,
        name:'digital-technologies',
        title:'Digital Technologies',
        description:'',
    },
    {
        id:16,
        name:'design-visual-communication',
        title:'D.V.C',
        description:'',
    },
    {
        id:17,
        name:'hard-materials',
        title:'Hard Materials',
        description:'',
    },
]   